title: Dr. Pothireddy Surendranath Reddy
description: >
  Orthopaedic Surgeon, Medical Educator, and Public Policy Analyst.
  Articles on healthcare, economics, global politics, and medical education.

author: Dr. Pothireddy Surendranath Reddy
email: ""
theme: minima

markdown: kramdown

minima:
  skin: classic
  social_links:
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/pothireddy-surendranath-reddy-a980b438a" }
    - { platform: twitter, user_url: "https://x.com/pothireddy1196" }
    - { platform: youtube, user_url: "https://www.youtube.com/@srp3597" }

header_pages:
  - index.md

plugins:
  - jekyll-seo-tag
